[package]
rust-version = "1.76"
name = "idiom"
version = "0.4.0"
edition = "2021"
include = [
    "src/**/*",
    "Cargo.toml",
    "LICENCE",
    "README.MD"
]
license = "MIT"
description = "Simple low config editor supporting LSP and syntax highlighting."
repository = "https://github.com/Dah-phd/idiom"
keywords = ["terminal", "edit", "lsp", "text"]
categories = ["development-tools", "text-editors"]
authors = ["Daniel Nikolaev <toolsproed@gmail.com>"]

[dependencies]
crossterm = "0.28.1"
lsp-types = "0.97.0"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.125"
tokio = { version="1.40.0", features=["rt", "macros", "rt-multi-thread", "process", "io-util"] }
tokio-util = { version="0.7.11", features = ["codec", "io"] }
tokio-stream = "0.1.15"
dirs = "5.0.1"
ignore = "0.4.22"
fuzzy-matcher = "0.3.7"
portable-pty = "0.8.1"
strip-ansi-escapes = "0.2.0"
bitflags = "2.6.0"
regex = "1.10.6"
thiserror = "1.0.63"
unicode-width = "0.1.13"
copypasta = "0.10.1"
notify = { version = "6.1.1", default-features = false, features = ["macos_kqueue"] }

[profile.dev]
debug = true
