[package]
rust-version = "1.76"
name = "idiom"
version = "0.4.4"
edition = "2021"
include = [
    "src/**/*",
    "Cargo.toml",
    "LICENCE",
    "README.MD"
]
license = "MIT"
description = "Simple low config editor supporting LSP and syntax highlighting."
repository = "https://github.com/Dah-phd/idiom"
keywords = ["terminal", "edit", "lsp", "text"]
categories = ["development-tools", "text-editors"]
authors = ["Daniel Nikolaev <toolsproed@gmail.com>"]

[dependencies]
clap = {version = "4.5.20", features = ["derive"]}
crossterm = "0.28.1"
lsp-types = "0.97.0"
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
toml = "0.8.19"
tokio = { version="1.41.0", features=["rt", "macros", "rt-multi-thread", "process", "io-util"] }
tokio-util = { version="0.7.12", features = ["codec", "io"] }
tokio-stream = "0.1.16"
dirs = "5.0.1"
ignore = "0.4.23"
fuzzy-matcher = "0.3.7"
portable-pty = "0.8.1"
strip-ansi-escapes = "0.2.0"
bitflags = "2.6.0"
regex = "1.11.1"
thiserror = "1.0.65"
unicode-width = "0.2.0"
copypasta = "0.10.1"
notify = { version = "7.0.0", default-features = false, features = ["macos_kqueue"] }
logos = "0.14.2"

[profile.dev]
debug = true
