[package]
name = "idiom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
lsp-types = "0.94.0"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
tokio = { version="1.28.0", features=["rt", "macros", "rt-multi-thread", "process", "io-util"] }
tokio-util = { version="0.7.7", features = ["codec", "io"] }
tokio-stream = "0.1.12"
ratatui = { version = "0.24.0", features = ["serde"] }
unicode-width = "0.1"
anyhow = "1.0.71"
dirs = "5.0.1"
reqwest = "0.11.20"
ignore = "0.4.20"
fuzzy-matcher = "0.3.7"
copypasta = "0.10"
