[package]
rust-version = "1.76"
name = "idiom"
version = "0.4.0"
edition = "2021"
include = [
    "src/**/*",
    "Cargo.toml",
    "LICENCE",
    "README.MD"
]
license = "MIT"
description = "Simple low config editor supporting LSP and syntax highlighting."
repository = "https://github.com/Dah-phd/idiom"
keywords = ["terminal", "edit", "lsp", "text"]
categories = ["development-tools", "text-editors"]
authors = ["Daniel Nikolaev <toolsproed@gmail.com>"]

[dependencies]
crossterm = "0.27.0"
lsp-types = "0.97.0" # still on version 0.95.0 (at this stage fluent-uri looks more annoying than uri)
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
tokio = { version="1.36.0", features=["rt", "macros", "rt-multi-thread", "process", "io-util"] }
tokio-util = { version="0.7.10", features = ["codec", "io"] }
tokio-stream = "0.1.15"
dirs = "5.0.1"
# reqwest = "0.11.20"  !TODO enable when autodownloading is created
ignore = "0.4.20"
fuzzy-matcher = "0.3.7"
copypasta = "0.10.1"
portable-pty = "0.8.1"
strip-ansi-escapes = "0.2.0"
bitflags = "2.4.2"
regex = "1.10.4"
thiserror = "1.0.60"
unicode-width = "0.1.12"

[profile.dev]
debug = true
